unl_breadcrumbs.settings:
  type: config_object
  mapping:
    site_root_breadcrumb_title:
      label: Site Root Breadcrumb Title
      type: string
    interstitial_breadcrumbs:
      label: Interstitial Breadcrumbs
      type: sequence
      sequence:
        label: Interstitial Item
        type: mapping
        mapping:
          title:
            label: Title
            type: string
          url:
            label: URL
            type: uri
